name: Push backend image to Image

on:
  [workflow_dispatch]
  # push:
  #   branches: 
  #     - main

jobs:
  build: 
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: paularinze/weather-app
        tags: build-${{ github.run_number }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
  updatemanifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: changing the deployment of git repo
        with:
          repository: 'paularinzee/node-manifest'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email arinzennajipaul@gmail.com
          git config user.name paularinzee
          pwd
          cat deployment.yaml
          pwd
          sed -i "s+paularinze/node-app.*+paularinze/node-app:build-$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}